// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";

import { ScreenVariantProvider } from "../components/plasmic/plasmic_zen/PlasmicGlobalVariant__Screen";
import { ThemesContext } from "../components/plasmic/plasmic_zen/PlasmicGlobalVariant__Themes";
import { ModeContext } from "../components/plasmic/plasmic_zen/PlasmicGlobalVariant__Mode";
import { Mode2Context } from "../components/plasmic/plasmic_zen/PlasmicGlobalVariant__Mode2";
import { BrandsContext } from "../components/plasmic/plasmic_zen/PlasmicGlobalVariant__Brands";
import { PlasmicComponents } from "../components/plasmic/plasmic_zen/PlasmicComponents";
import { useRouter } from "next/router";

function Components() {
  // Use PlasmicComponents to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicComponents are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicComponents is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <BrandsContext.Provider value={undefined}>
      <Mode2Context.Provider value={undefined}>
        <ModeContext.Provider value={undefined}>
          <ThemesContext.Provider value={undefined}>
            <PageParamsProvider__
              route={useRouter()?.pathname}
              params={useRouter()?.query}
              query={useRouter()?.query}
            >
              <PlasmicComponents />
            </PageParamsProvider__>
          </ThemesContext.Provider>
        </ModeContext.Provider>
      </Mode2Context.Provider>
    </BrandsContext.Provider>
  );
}

export default Components;
