// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q9SbVKdQNQqS8hT1VyyZBb
// Component: yFeUkyBl876T

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_plasmic_zen.module.css"; // plasmic-import: q9SbVKdQNQqS8hT1VyyZBb/projectcss
import sty from "./PlasmicHomepage2.module.css"; // plasmic-import: yFeUkyBl876T/css

createPlasmicElementProxy;

export type PlasmicHomepage2__VariantMembers = {};
export type PlasmicHomepage2__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage2__VariantsArgs;
export const PlasmicHomepage2__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage2__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage2__ArgsType;
export const PlasmicHomepage2__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage2__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultHomepage2Props {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage2__RenderFunc(props: {
  variants: PlasmicHomepage2__VariantsArgs;
  args: PlasmicHomepage2__ArgsType;
  overrides: PlasmicHomepage2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__oOjwu)}
      >
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.columns__ewre3)}
        >
          <div className={classNames(projectcss.all, sty.column__ljuc)}>
            <div className={classNames(projectcss.all, sty.freeBox___82SDu)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xYlFy
                )}
              >
                {"shadow.primary.100"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__oI6Sx)}>
            <div className={classNames(projectcss.all, sty.freeBox__o4Vw9)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zw1Rx
                )}
              >
                {"shadow.primary.200"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__gxfs7)}>
            <div className={classNames(projectcss.all, sty.freeBox__vPTs)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iEva
                )}
              >
                {"shadow.primary.300"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__sM1Ep)}>
            <div className={classNames(projectcss.all, sty.freeBox___8Esbp)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vgJrj
                )}
              >
                {"shadow.primary.400"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__rU3Qx)}>
            <div className={classNames(projectcss.all, sty.freeBox__nyu5B)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__faL4Z
                )}
              >
                {"shadow.primary.500"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__apwPr)}>
            <div className={classNames(projectcss.all, sty.freeBox__rcnvn)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9BiLu
                )}
              >
                {"shadow.primary.600"}
              </div>
            </div>
          </div>
        </Stack__>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__uqcSr)}
      >
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.columns___1CwwT)}
        >
          <div className={classNames(projectcss.all, sty.column__cMaQ2)}>
            <div className={classNames(projectcss.all, sty.freeBox__k6URu)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__snbIo
                )}
              >
                {"shadow.secondary.100"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__fz486)}>
            <div className={classNames(projectcss.all, sty.freeBox___3Gzu9)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__z80I3
                )}
              >
                {"shadow.secondary.200"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__zGc0N)}>
            <div className={classNames(projectcss.all, sty.freeBox__aU15D)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pdw5K
                )}
              >
                {"shadow.secondary.300"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column___4X48M)}>
            <div className={classNames(projectcss.all, sty.freeBox__rL8N)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eYw2P
                )}
              >
                {"shadow.secondary.400"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__smUhA)}>
            <div className={classNames(projectcss.all, sty.freeBox__t0ZY2)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tpRcG
                )}
              >
                {"shadow.secondary.500"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__s7Hia)}>
            <div className={classNames(projectcss.all, sty.freeBox__z5J3I)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yOqZx
                )}
              >
                {"shadow.secondary.600"}
              </div>
            </div>
          </div>
        </Stack__>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__igKyq)}
      >
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.columns___1WJjl)}
        >
          <div className={classNames(projectcss.all, sty.column__qnJs)}>
            <div className={classNames(projectcss.all, sty.freeBox__kQyB2)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aJbe
                )}
              >
                {"shadow.none"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__sBj8)} />

          <div className={classNames(projectcss.all, sty.column__sf0Dg)} />

          <div className={classNames(projectcss.all, sty.column__lU9V0)} />

          <div className={classNames(projectcss.all, sty.column__tC0S3)} />

          <div className={classNames(projectcss.all, sty.column__ujrXu)} />
        </Stack__>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__v2Pq)}
      >
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.columns__mS4Tv)}
        >
          <div className={classNames(projectcss.all, sty.column___6NDjd)}>
            <div className={classNames(projectcss.all, sty.freeBox__ep6L7)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wpZzF
                )}
              >
                {"radii.50"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column___6YePv)}>
            <div className={classNames(projectcss.all, sty.freeBox__ct2Vp)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wyQxo
                )}
              >
                {"radii.75"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__plVyV)}>
            <div className={classNames(projectcss.all, sty.freeBox___4Lz2)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ypy0L
                )}
              >
                {"radii.100"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__yhbaI)}>
            <div className={classNames(projectcss.all, sty.freeBox__iTc0B)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__oOjAg
                )}
              >
                {"radii.150"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__epfF)}>
            <div className={classNames(projectcss.all, sty.freeBox___4JsSh)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rczJf
                )}
              >
                {"radii.200"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column___5FCi9)}>
            <div className={classNames(projectcss.all, sty.freeBox__rY8Qb)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nqqLc
                )}
              >
                {"radii.250"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__y8Hgq)}>
            <div className={classNames(projectcss.all, sty.freeBox__xGbH)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0MfdS
                )}
              >
                {"radii.300"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__yHq8E)}>
            <div className={classNames(projectcss.all, sty.freeBox__gpUAr)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wbrMk
                )}
              >
                {"radii.400"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__bGnP)}>
            <div className={classNames(projectcss.all, sty.freeBox__qpVpR)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nvVvu
                )}
              >
                {"radii.500"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__j1CB)}>
            <div className={classNames(projectcss.all, sty.freeBox__ik7AF)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__b5Gh6
                )}
              >
                {"radii.600"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column___6ZlW)}>
            <div className={classNames(projectcss.all, sty.freeBox___9IvDs)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hPhVr
                )}
              >
                {"radii.800"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__s1Lxm)}>
            <div className={classNames(projectcss.all, sty.freeBox__zukAq)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qXnaw
                )}
              >
                {"radii.none"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__vmZj)}>
            <div className={classNames(projectcss.all, sty.freeBox__iiwWm)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jCQtu
                )}
              >
                {"radii.round"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__y1PSh)}>
            <div className={classNames(projectcss.all, sty.freeBox__vnBn8)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4MxJ
                )}
              >
                {"radii.base"}
              </div>
            </div>
          </div>
        </Stack__>
      </Stack__>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox___6JnG)}
      >
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.columns__h0PsL)}
        >
          <div className={classNames(projectcss.all, sty.column__sGw3)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__sq1E0)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__i4Gif)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oj3Ns
                  )}
                >
                  {"space.25"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__rkz05)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lzvH1
                  )}
                >
                  {"space.25"}
                </div>
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__gmlXf)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__zNrs5)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7ZvKu
                  )}
                >
                  {"space.100"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___18JWw)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nz3AA
                  )}
                >
                  {"space.100"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__y3QXm)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__pB9Kh)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___6ThrE)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vlde0
                  )}
                >
                  {"space.150"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___7HSY)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kYvg
                  )}
                >
                  {"space.150"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column___9RWf)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__rx8Ii)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__s2Qn)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__itiHh
                  )}
                >
                  {"space.200"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__qRhr4)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__knUYl
                  )}
                >
                  {"space.200"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__vnpoH)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__oWem3)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___9Eipe)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__orh7X
                  )}
                >
                  {"space.250"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__jjUA)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__j9XG
                  )}
                >
                  {"space.250"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__ibAze)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ugXK)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__anH3A)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ptLGd
                  )}
                >
                  {"space.300"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__fjaWl)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ntqaj
                  )}
                >
                  {"space.300"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__am2Tl)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__vEdr)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__rq4J1)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sfmNw
                  )}
                >
                  {"space.400"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__kcVnE)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b0Fo
                  )}
                >
                  {"space.400"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__ozrTs)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__zoSa7)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__vs7K)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Zab5
                  )}
                >
                  {"space.500"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__g2IXf)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tWqpc
                  )}
                >
                  {"space.500"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__xm94S)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__oAfs)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__vg4Pz)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5GFal
                  )}
                >
                  {"space.600"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___8IUy9)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ajuJ0
                  )}
                >
                  {"space.600"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__qQoM5)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__bgUt1)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__zl6Bl)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lrLNr
                  )}
                >
                  {"space.700"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__yskGg)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___99G1J
                  )}
                >
                  {"space.700"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__glU0E)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__lZph0)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__vRxCp)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rwPua
                  )}
                >
                  {"space.800"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__xBf4R)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e42M8
                  )}
                >
                  {"space.800"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__v26Jx)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__bA9T)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__xKkN)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2Ypj
                  )}
                >
                  {"space.900"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___7DCzP)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q7SGa
                  )}
                >
                  {"space.900"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__w5Mi)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___3Ucee)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__vtiRx)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lUTss
                  )}
                >
                  {"space.1000"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__fVrm6)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__srs0J
                  )}
                >
                  {"space.1000"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__pdAmP)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___2SCuc)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__y5GQb)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sXvNr
                  )}
                >
                  {"space.1200"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__jt6K8)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ukkr0
                  )}
                >
                  {"space.1200"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__nOXbZ)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__pnju)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__bY5ME)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dkzpr
                  )}
                >
                  {"space.1600"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__hqaaa)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cIy3U
                  )}
                >
                  {"space.1600"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__jRbZ3)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__t3Twz)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__xxnSa)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mJihI
                  )}
                >
                  {"space.2000"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___1Xwtn)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w7GuR
                  )}
                >
                  {"space.2000"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__zJm9A)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__wOZgX)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__zRxvg)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wzTsh
                  )}
                >
                  {"space.2200"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___1QB7H)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xr1S5
                  )}
                >
                  {"space.2200"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__xgKjU)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___1UgJ2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___33Wa0)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Rv1L
                  )}
                >
                  {"space.2600"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__siIbH)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iEa
                  )}
                >
                  {"space.2600"}
                </div>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.column__mhQvc)}>
            <div className={classNames(projectcss.all, sty.freeBox___4LO8K)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cp5Ce
                )}
              >
                {"space.base"}
              </div>
            </div>
          </div>
        </Stack__>
      </Stack__>
      <div className={classNames(projectcss.all, sty.freeBox__pl6I5)}>
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.columns__seqTj)}
        >
          <div className={classNames(projectcss.all, sty.column___61ReC)}>
            <div className={classNames(projectcss.all, sty.freeBox__l0Al2)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hFwg
                )}
              >
                {"borderWidth.100"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column___0AytF)}>
            <div className={classNames(projectcss.all, sty.freeBox___2U7E)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uGeqp
                )}
              >
                {"borderWidth.200"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column___1LSyd)}>
            <div className={classNames(projectcss.all, sty.freeBox__lb0FO)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aJb4M
                )}
              >
                {"borderWidth.400"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__bcqYr)}>
            <div className={classNames(projectcss.all, sty.freeBox__oUFna)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0Tmgt
                )}
              >
                {"borderWidth.none"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__fu0Na)}>
            <div className={classNames(projectcss.all, sty.freeBox___0IWf)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__x1FQo
                )}
              >
                {"borderWidth.sm"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__uGiKf)}>
            <div className={classNames(projectcss.all, sty.freeBox__gHkDg)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qXvP
                )}
              >
                {"borderWidth.md"}
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.column__ib9Af)}>
            <div className={classNames(projectcss.all, sty.freeBox___1BHvU)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__c5Tit
                )}
              >
                {"borderWidth.200"}
              </div>
            </div>
          </div>
        </Stack__>
      </div>
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__ciDui)}
      >
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.columns___96DJd)}
        >
          <div className={classNames(projectcss.all, sty.column__zlTiS)}>
            <div className={classNames(projectcss.all, sty.freeBox__j0DOn)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mLpvz
                )}
              >
                {"borderWidth.100"}
              </div>
            </div>
          </div>
        </Stack__>
      </Stack__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage2__VariantsArgs;
    args?: PlasmicHomepage2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage2__ArgProps,
          internalVariantPropNames: PlasmicHomepage2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage2";
  } else {
    func.displayName = `PlasmicHomepage2.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage2 = Object.assign(
  // Top-level PlasmicHomepage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHomepage2
    internalVariantProps: PlasmicHomepage2__VariantProps,
    internalArgProps: PlasmicHomepage2__ArgProps
  }
);

export default PlasmicHomepage2;
/* prettier-ignore-end */
