// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q9SbVKdQNQqS8hT1VyyZBb
// Component: td1UH1xT-FX0

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_plasmic_zen.module.css"; // plasmic-import: q9SbVKdQNQqS8hT1VyyZBb/projectcss
import sty from "./PlasmicLogomark.module.css"; // plasmic-import: td1UH1xT-FX0/css

import LogoiconOnlyIcon from "./icons/PlasmicIcon__LogoiconOnly"; // plasmic-import: f-X_MCNxficR/icon
import LogoiconTextSinglelineIcon from "./icons/PlasmicIcon__LogoiconTextSingleline"; // plasmic-import: U4mlIA00Js3I/icon
import LogoiconTextMultilineIcon from "./icons/PlasmicIcon__LogoiconTextMultiline"; // plasmic-import: ZN57_np0aamI/icon

createPlasmicElementProxy;

export type PlasmicLogomark__VariantMembers = {
  styled: "multiLine" | "singleLine";
};
export type PlasmicLogomark__VariantsArgs = {
  styled?: SingleChoiceArg<"multiLine" | "singleLine">;
};
type VariantPropType = keyof PlasmicLogomark__VariantsArgs;
export const PlasmicLogomark__VariantProps = new Array<VariantPropType>(
  "styled"
);

export type PlasmicLogomark__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicLogomark__ArgsType;
export const PlasmicLogomark__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2"
);

export type PlasmicLogomark__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultLogomarkProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  styled?: SingleChoiceArg<"multiLine" | "singleLine">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogomark__RenderFunc(props: {
  variants: PlasmicLogomark__VariantsArgs;
  args: PlasmicLogomark__ArgsType;
  overrides: PlasmicLogomark__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "styled",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.styled
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <LogoiconOnlyIcon
            className={classNames(projectcss.all, sty.svg__pqie)}
            role={"img"}
          />
        ),

        value: args.children
      })}
      {renderPlasmicSlot({
        defaultContents: (
          <LogoiconTextSinglelineIcon
            className={classNames(projectcss.all, sty.svg__sCp3R)}
            role={"img"}
          />
        ),

        value: args.slot
      })}
      {renderPlasmicSlot({
        defaultContents: (
          <LogoiconTextMultilineIcon
            className={classNames(projectcss.all, sty.svg__nZrG)}
            role={"img"}
          />
        ),

        value: args.slot2
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogomark__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogomark__VariantsArgs;
    args?: PlasmicLogomark__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLogomark__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLogomark__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogomark__ArgProps,
          internalVariantPropNames: PlasmicLogomark__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogomark__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogomark";
  } else {
    func.displayName = `PlasmicLogomark.${nodeName}`;
  }
  return func;
}

export const PlasmicLogomark = Object.assign(
  // Top-level PlasmicLogomark renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicLogomark
    internalVariantProps: PlasmicLogomark__VariantProps,
    internalArgProps: PlasmicLogomark__ArgProps
  }
);

export default PlasmicLogomark;
/* prettier-ignore-end */
