// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q9SbVKdQNQqS8hT1VyyZBb
// Component: W-hSwvEACG2N

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ThemesValue, useThemes } from "./PlasmicGlobalVariant__Themes"; // plasmic-import: Vhu4RsGekfQO/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_plasmic_zen.module.css"; // plasmic-import: q9SbVKdQNQqS8hT1VyyZBb/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: W-hSwvEACG2N/css

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  section?: Flex__<"section">;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    themes: useThemes()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root,
            {
              [sty.rootglobal_themes_dark]: hasVariant(
                globalVariants,
                "themes",
                "dark"
              ),
              [sty.rootglobal_themes_light]: hasVariant(
                globalVariants,
                "themes",
                "light"
              )
            }
          )}
        >
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__tG5C)}
          >
            <div className={classNames(projectcss.all, sty.column__oj9Qo)}>
              <div className={classNames(projectcss.all, sty.freeBox___4DhUw)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xjco
                  )}
                >
                  {"semantic.Shadow.none"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column__qLiHc)}>
              <div className={classNames(projectcss.all, sty.freeBox__pOlpZ)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wru5A
                  )}
                >
                  {""}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column__kz4CR)}>
              <div className={classNames(projectcss.all, sty.freeBox__uVo9U)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ivHom
                  )}
                >
                  {""}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column__hYkI)}>
              <div className={classNames(projectcss.all, sty.freeBox__pTg5T)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3DruT
                  )}
                >
                  {""}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column__fkY3H)}>
              <div className={classNames(projectcss.all, sty.freeBox__hjcL8)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__diaDs
                  )}
                >
                  {""}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column__hlmsa)}>
              <div className={classNames(projectcss.all, sty.freeBox___9D5Vq)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aHeBs
                  )}
                >
                  {""}
                </div>
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__s8NY)}
          >
            <div className={classNames(projectcss.all, sty.column___18Ra2)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__yLacb)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___6Ke23)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iKv7D
                    )}
                  >
                    {"semantic.fontWeights.headlines.bold"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__xeWtT)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hoSdU
                    )}
                  >
                    {"semantic.fontWeights.headlines.regular"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__fcPud)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ujjU
                    )}
                  >
                    {"semantic.fontWeights.headlines.semi-bold"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___0ZsXy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qePqm
                    )}
                  >
                    {"semantic.fontWeights.headlines.semi-medium"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__yGe70)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oslNb
                    )}
                  >
                    {"semantic.fontWeights.body.bold"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__rV65G)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cMn0
                    )}
                  >
                    {"semantic.fontWeights.body.regular"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___1DRo)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__acHrM
                    )}
                  >
                    {"semantic.fontWeights.body.semi-bold"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__q0Hk)}
          >
            <div className={classNames(projectcss.all, sty.column__sHhqm)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__d1Qrm)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__gYeuz)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rEvxw
                    )}
                  >
                    {"semantic.letterSpacing.body"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___5JPie)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fs0Ky
                    )}
                  >
                    {"semantic.letterSpacing.headlines"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__nymvv)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5Doe7
                    )}
                  >
                    {"semantic.letterSpacing.buttons"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__hirIe)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7QBnZ
                    )}
                  >
                    {"semantic.letterSpacing.captions"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__rdGKu)}
          >
            <div className={classNames(projectcss.all, sty.column__gFg)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vf9Hl)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__pVu0B)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nl85S
                    )}
                  >
                    {"semantic.textCase.none"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wCbmL)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iJLd
                    )}
                  >
                    {"semantic.textCase.captions"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__iHcqZ)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l2M1F
                    )}
                  >
                    {"semantic.textCase.buttons"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__kIuy)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8S9R6
                    )}
                  >
                    {"semantic.textCase.headlines"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__bRrLt)}
          >
            <div className={classNames(projectcss.all, sty.column__t4RdZ)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ebItl)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__xm0Mf)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__v84V
                    )}
                  >
                    {"semantic.textDecoration.none"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__riqVk)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eVnUl
                    )}
                  >
                    {"semantic.textDecoration.buttons"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wL8Jn)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aDkll
                    )}
                  >
                    {"semantic.textDecoration.captions"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__igyJq)}
          >
            <div className={classNames(projectcss.all, sty.column___4M0W0)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__dXmz2)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__dStBf)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__n49Yi
                    )}
                  >
                    {"semantic.typography.colossus.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___8Eo74)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__fnk5R)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__sQdAh)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cPjc
                    )}
                  >
                    {"semantic.typography.colossus.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__vTEr8)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__dwXli)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ekJxb)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__flP2N
                    )}
                  >
                    {"semantic.typography.display.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___5Mzk2)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__lwZt6)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__cdDkq)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vBb3X
                    )}
                  >
                    {"semantic.typography.display.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___3Pv5E)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__xzaaS)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__nX2L9)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mhjVt
                    )}
                  >
                    {"semantic.typography.hero.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___3RdIb)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sh0VQ)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__a7QpA)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5W2HT
                    )}
                  >
                    {"semantic.typography.hero.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__jxPy)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__c3Jyj)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__pzfX)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kjT7C
                    )}
                  >
                    {"semantic.typography.uber.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___3TY8U)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uicGc)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__aTzGn)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__naOhc
                    )}
                  >
                    {"semantic.typography.uber.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__jvku)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__mKRk8)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__eQ69G)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9GmhP
                    )}
                  >
                    {"semantic.typography.headline-1.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__vwUFy)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__dBtm)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__s4E21)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rh6Hg
                    )}
                  >
                    {"semantic.typography.headline-1.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__bjiHz)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__b1NFi)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__lwAm3)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zOFz
                    )}
                  >
                    {"semantic.typography.headline-2.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__caT10)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6MkGa)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___4EbFa)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gbciR
                    )}
                  >
                    {"semantic.typography.headline-2.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__g312P)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___7YB1R)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___67Ooo)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ycDhZ
                    )}
                  >
                    {"semantic.typography.headline-2.medium"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__mlSNc)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kXmRp)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__hiCpL)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aGlpQ
                    )}
                  >
                    {"semantic.typography.headline-3.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__kSfhV)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ml8DX)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__nZj04)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wA65P
                    )}
                  >
                    {"semantic.typography.headline-3.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__r3ALg)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__y1T70)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___745Wj)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__abX38
                    )}
                  >
                    {"semantic.typography.headline-4.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__ru7P)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jqKyS)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__lnDiv)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ylRYv
                    )}
                  >
                    {"semantic.typography.headline-4.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___1XpLa)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__axL0Y)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__i6Re2)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xGny3
                    )}
                  >
                    {"semantic.typography.headline-5.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__uSqEz)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__hqAmd)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___86D0L)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f3QJw
                    )}
                  >
                    {"semantic.typography.headline-5.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__q63Em)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__q4I7B)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__cg9Nr)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vEkdO
                    )}
                  >
                    {"semantic.typography.lead.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__xrnGh)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__cb9N9)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__gPtYu)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c9DmF
                    )}
                  >
                    {"semantic.typography.lead.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__fw6G)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jgYq3)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__l8Gkk)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oCp7R
                    )}
                  >
                    {"semantic.typography.body.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__p2Dc)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kbzXl)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__vxa2)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eOeTy
                    )}
                  >
                    {"semantic.typography.body.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__gg9W7)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__gRv5X)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__dd0O)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__da8Ge
                    )}
                  >
                    {"semantic.typography.small.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___3H4P8)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jcjPg)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__tuxvK)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gkXqO
                    )}
                  >
                    {"semantic.typography.small.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___90Ric)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6Up2S)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__rza4P)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oa2Zi
                    )}
                  >
                    {"semantic.typography.caption.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__yeZua)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kdvNp)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ekbXq)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hfzt2
                    )}
                  >
                    {"semantic.typography.caption.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__gbugf)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__cYsNl)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__sJtzu)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mEld5
                    )}
                  >
                    {"semantic.typography.caption.semi-bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__mUjnJ)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__yAg2F)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__jsBhq)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___33ISv
                    )}
                  >
                    {"semantic.typography.x-small.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___7BcxD)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__in7V9)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__gXyq)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5BrZq
                    )}
                  >
                    {"semantic.typography.x-small.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__rxCao)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__gkTtM)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__tYwHc)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__shc3U
                    )}
                  >
                    {"semantic.typography.tiny.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__nZdzd)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6M4Jm)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__dk92V)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l0Ai
                    )}
                  >
                    {"semantic.typography.tiny.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__ocRgC)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__cr3Wk)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__vzWnj)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1KCsn
                    )}
                  >
                    {"semantic.typography.button.normal.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__pQjci)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kxquM)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__lxEv)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t0VC7
                    )}
                  >
                    {"semantic.typography.button.normal.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___48H9D)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__q0Tl2)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___54BkA)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fNkz7
                    )}
                  >
                    {"semantic.typography.button.large.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__aAt8)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___55H06)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ek2Fw)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zSkwe
                    )}
                  >
                    {"semantic.typography.button.large.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__t20D9)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jlkIn)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__aiRq7)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8Lq5N
                    )}
                  >
                    {"semantic.typography.button.x-large.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__dluGb)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__mYpsm)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__gP8Y)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jkU2Z
                    )}
                  >
                    {"semantic.typography.button.x-large.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__llHq)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__iNBkJ)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__z3NUr)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__agL7G
                    )}
                  >
                    {"semantic.typography.input.normal.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___4LWuN)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__dIoTo)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__hbHY)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rGajL
                    )}
                  >
                    {"semantic.typography.input.normal.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__dvvc7)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__apuJr)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__xopMt)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pq3S
                    )}
                  >
                    {"semantic.typography.input.large.bold"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__orqCt)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___9Kudn)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__oa68)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wpFuI
                    )}
                  >
                    {"semantic.typography.input.large.regular"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__mJmXw)}
          >
            <div className={classNames(projectcss.all, sty.column__tghRv)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__hVuYr)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__soIfv)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kE7Gf
                    )}
                  >
                    {"semantic.ui.border-radius"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__bbPz)}
          >
            <div className={classNames(projectcss.all, sty.column___151Mf)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rFvS8)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___92BPs)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gx11Y
                    )}
                  >
                    {"semantic.comp.border-radius"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__hdgxc)}
          >
            <div className={classNames(projectcss.all, sty.column__zi9H8)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__c4N8R)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___12Ysw)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dVgvj
                    )}
                  >
                    {"semantic.border-width.none"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__hUmH)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__x4RKt)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__c6Xi)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f5BCq
                    )}
                  >
                    {"semantic.border-width.default"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__knrda)}
          >
            <div className={classNames(projectcss.all, sty.column__c7Ve)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ubEn5)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__vedWg)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hPsf
                    )}
                  >
                    {"semantic.space-between.comp.xs"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__dz16B)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___057W1
                    )}
                  >
                    {"semantic.space-between.comp.xs"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__kqe0E)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__i6GBp)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__qrUeO)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hrLzw
                    )}
                  >
                    {"semantic.space-between.comp.sm"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__nk1Ho)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f0YrI
                    )}
                  >
                    {"semantic.space-between.comp.sm"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__fVAj7)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bnuHa)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__zihvQ)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hudjm
                    )}
                  >
                    {"semantic.space-between.comp.md"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___2H2G9)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bNqhp
                    )}
                  >
                    {"semantic.space-between.comp.md"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__ls28W)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rPemT)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___3SzVi)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__voEm5
                    )}
                  >
                    {"semantic.space-between.pattern.xs"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__yRIcX)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___494On
                    )}
                  >
                    {"semantic.space-between.pattern.xs"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__k7Nzx)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qKCI)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__hcUcc)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ev8Mj
                    )}
                  >
                    {"semantic.space-between.pattern.sm"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__k4OwU)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rzOug
                    )}
                  >
                    {"semantic.space-between.pattern.sm"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__uRt7Y)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__m78Aa)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__oYm46)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zMmJz
                    )}
                  >
                    {"semantic.space-between.pattern.md"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__acv3Y)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qArWw
                    )}
                  >
                    {"semantic.space-between.pattern.md"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___1RedG)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__srjCd)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__l54Lz)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3Nm6R
                    )}
                  >
                    {"semantic.space-between.pattern.lg"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__g2Upj)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__alI8E
                    )}
                  >
                    {"semantic.space-between.pattern.lg"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column___2TVk8)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bjGgi)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__o02Wg)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gfv85
                    )}
                  >
                    {"semantic.space-between.pattern.xl"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__e4Jrk)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yGZk
                    )}
                  >
                    {"semantic.space-between.pattern.xl"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__xzBsf)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___9Tlts)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__niaqq)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__osmGk
                    )}
                  >
                    {"semantic.space-between.section.xxs"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__eEVkm)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tf7YM
                    )}
                  >
                    {"semantic.space-between.section.xxs"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__puiuh)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__hde6F)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__kd46T)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hAkH
                    )}
                  >
                    {"semantic.space-between.section.xs"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__zdMAy)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hh67
                    )}
                  >
                    {"semantic.space-between.section.xs"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__fL5S)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__j4U3)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ffCgI)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nEfge
                    )}
                  >
                    {"semantic.space-between.section.sm"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__aCgp0)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wJwF
                    )}
                  >
                    {"semantic.space-between.section.sm"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__h2KkY)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qjyj2)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__bRk9)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tquzq
                    )}
                  >
                    {"semantic.space-between.section.md"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__eGaby)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9OLK
                    )}
                  >
                    {"semantic.space-between.section.md"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__fjwep)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___7ToQ0)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__mdsY2)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uCaDh
                    )}
                  >
                    {"semantic.space-between.section.lg"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__v52Sj)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lVlKo
                    )}
                  >
                    {"semantic.space-between.section.lg"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__oySno)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wUc)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__eo5EJ)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1BrEj
                    )}
                  >
                    {"semantic.space-between.section.xl"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__jeuVh)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__urH3
                    )}
                  >
                    {"semantic.space-between.section.xl"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__eH2Mb)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uxQ26)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__sKea9)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__shmYl
                    )}
                  >
                    {"semantic.space-between.section.xxl"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__dxiBg)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aoVjs
                    )}
                  >
                    {"semantic.space-between.section.xxl"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__expno)}
          >
            <div className={classNames(projectcss.all, sty.column__yrtxt)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jzKF)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__vfmVn)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yaiKg
                    )}
                  >
                    {"semantic.space-around.comp.sm"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__d3YCi)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__tj4Xe)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__kYxo9)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pwS6C
                    )}
                  >
                    {"semantic.space-around.comp.md"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__aQIs)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qkoPl)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___3LxY4)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lhK7Z
                    )}
                  >
                    {"semantic.space-around.comp.lg"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__giA6L)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__nekn3)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__wLsi4)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ai2Au
                    )}
                  >
                    {"semantic.space-around.pattern.md"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__zdsWh)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uu3Dc)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__mg3Nw)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dzCgQ
                    )}
                  >
                    {"semantic.space-around.section.xxs"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__bhi5P)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__cblwb)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__fP5So)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dS5KH
                    )}
                  >
                    {"semantic.space-around.section.xs"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__gn3Mx)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__tcf0R)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___71FNt)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yaIwG
                    )}
                  >
                    {"semantic.space-around.section.sm"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__r4JLp)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__gQhd)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__bmFup)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0XyKe
                    )}
                  >
                    {"semantic.space-around.section.md"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__hSkdw)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__xtUpT)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__mFtAt)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2R9H
                    )}
                  >
                    {"semantic.space-around.section.lg"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__cVjZ)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__nt3Y)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__syuRm)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yKmXo
                    )}
                  >
                    {"semantic.space-around.section.xl"}
                  </div>
                </div>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.column__xotUv)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___8GvMb)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__xUnvx)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gnXx
                    )}
                  >
                    {"semantic.space-around.section.xxl"}
                  </div>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "section"],
  section: ["section"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  section: "section";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
